definitions:
  models.AuthenticationRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
  description: API Server for  Gamers Assessment web-application
  title: Registration, authentication and authorization API
  version: beta 0.1
paths:
  /api/auth/log:
    post:
      consumes:
      - application/json
      description: accepts json sent by the user as input and authorize it
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AuthenticationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 'message: Authentication was successful; access_token'
        "400":
          description: 'error: Failed to read body'
        "403":
          description: 'fail": "You entered the wrong password or email'
      summary: authenticates the user
      tags:
      - authentication
  /api/auth/ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: plain
      summary: ping example
      tags:
      - example
  /api/auth/registration:
    post:
      consumes:
      - application/json
      description: accepts json sent by the user as input and registers it
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 'message: Registration was successful'
        "400":
          description: 'error: Failed to read body'
        "409":
          description: 'fail: This email already exists'
        "422":
          description: 'fail: Your password is not valid'
        "500":
          description: 'error: Error on the server. Please, try again later'
      summary: registers a user
      tags:
      - registration
swagger: "2.0"
